/* This file is automatically generated by Lemon from input grammar
** source file "src/xon.lemon".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifier prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 46 "src/xon.lemon"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct XonExpr XonExpr;

typedef enum {
    XON_EXPR_IDENTIFIER,
    XON_EXPR_BINARY,
    XON_EXPR_UNARY,
    XON_EXPR_CALL,
    XON_EXPR_MEMBER,
    XON_EXPR_TERNARY,
    XON_EXPR_IF,
    XON_EXPR_FUNCTION
} XonExprKind;

typedef enum {
    XON_EXPR_OP_OR,
    XON_EXPR_OP_AND,
    XON_EXPR_OP_EQ,
    XON_EXPR_OP_NEQ,
    XON_EXPR_OP_LT,
    XON_EXPR_OP_LTE,
    XON_EXPR_OP_GT,
    XON_EXPR_OP_GTE,
    XON_EXPR_OP_ADD,
    XON_EXPR_OP_SUB,
    XON_EXPR_OP_MUL,
    XON_EXPR_OP_DIV,
    XON_EXPR_OP_MOD,
    XON_EXPR_OP_NULLISH,
    XON_EXPR_OP_NEG,
    XON_EXPR_OP_NOT,
    XON_EXPR_OP_UNARY_PLUS
} XonExprOp;

struct XonExpr {
    XonExprKind kind;
    int line;
    union {
        char* identifier_name;

        struct {
            XonExprOp op;
            struct DataNode* left;
            struct DataNode* right;
        } binary;

        struct {
            XonExprOp op;
            struct DataNode* operand;
        } unary;

        struct {
            struct DataNode* callee;
            struct DataNode* args;
        } call;

        struct {
            struct DataNode* object;
            char* member;
        } member;

        struct {
            struct DataNode* cond;
            struct DataNode* then_expr;
            struct DataNode* else_expr;
        } ternary;

        struct {
            struct DataNode* params;
            struct DataNode* body;
        } function;
    } u;
};

typedef enum {
    TYPE_OBJECT,
    TYPE_LIST,
    TYPE_STRING,
    TYPE_NUMBER,
    TYPE_BOOL,
    TYPE_NULL,
    TYPE_EXPR,
    TYPE_DECL,
    TYPE_FUNCTION
} DataType;

typedef struct DataNode {
    DataType type;
    struct DataNode* next;
    union {
        char* s_val;
        double n_val;
        int b_val;
        struct {
            struct DataNode* key;
            struct DataNode* value;
        } aggregate;

        struct {
            int is_const;
            char* name;
            struct DataNode* init_expr;
        } declaration;

        XonExpr* expr;
        void* function_data;
    } data;
} DataNode;

typedef struct Token {
    char* s_val;
    double n_val;
    int line;
} Token;

typedef void (*XonSyntaxErrorHandler)(int line, const char* token, void* user_data);

typedef struct ParserState {
    struct DataNode** result;
    int had_error;
    XonSyntaxErrorHandler on_syntax_error;
    void* user_data;
} ParserState;

DataNode* new_node(DataType type) {
    DataNode* n = (DataNode*)malloc(sizeof(DataNode));
    if (n) {
        memset(n, 0, sizeof(DataNode));
        n->type = type;
    }
    return n;
}

DataNode* link_node(DataNode* head, DataNode* item) {
    if (!head) return item;
    DataNode* current = head;
    while (current->next) {
        current = current->next;
    }
    current->next = item;
    return head;
}

static DataNode* new_pair_node(const char* key, DataNode* value) {
    DataNode* node = new_node(TYPE_OBJECT);
    if (!node) return NULL;
    node->data.aggregate.key = new_node(TYPE_STRING);
    if (!node->data.aggregate.key) {
        free(node);
        return NULL;
    }
    node->data.aggregate.key->data.s_val = (char*)key;
    node->data.aggregate.value = value;
    return node;
}

DataNode* new_list_node(DataNode* first_item) {
    DataNode* list = new_node(TYPE_LIST);
    if (!list) return NULL;
    list->data.aggregate.value = first_item;
    return list;
}

DataNode* new_expr_node(XonExpr* expr) {
    DataNode* n = new_node(TYPE_EXPR);
    if (!n) return NULL;
    n->data.expr = expr;
    return n;
}

XonExpr* xon_expr_identifier(const char* name, int line) {
    XonExpr* expr = (XonExpr*)malloc(sizeof(XonExpr));
    if (!expr) return NULL;
    expr->kind = XON_EXPR_IDENTIFIER;
    expr->line = line;
    expr->u.identifier_name = (char*)name;
    return expr;
}

XonExpr* xon_expr_binary(XonExprOp op, DataNode* left, DataNode* right, int line) {
    XonExpr* expr = (XonExpr*)malloc(sizeof(XonExpr));
    if (!expr) return NULL;
    expr->kind = XON_EXPR_BINARY;
    expr->line = line;
    expr->u.binary.op = op;
    expr->u.binary.left = left;
    expr->u.binary.right = right;
    return expr;
}

XonExpr* xon_expr_unary(XonExprOp op, DataNode* operand, int line) {
    XonExpr* expr = (XonExpr*)malloc(sizeof(XonExpr));
    if (!expr) return NULL;
    expr->kind = XON_EXPR_UNARY;
    expr->line = line;
    expr->u.unary.op = op;
    expr->u.unary.operand = operand;
    return expr;
}

XonExpr* xon_expr_member(DataNode* object, const char* member, int line) {
    XonExpr* expr = (XonExpr*)malloc(sizeof(XonExpr));
    if (!expr) return NULL;
    expr->kind = XON_EXPR_MEMBER;
    expr->line = line;
    expr->u.member.object = object;
    expr->u.member.member = (char*)member;
    return expr;
}

XonExpr* xon_expr_ternary(DataNode* cond, DataNode* then_expr, DataNode* else_expr, int line) {
    XonExpr* expr = (XonExpr*)malloc(sizeof(XonExpr));
    if (!expr) return NULL;
    expr->kind = XON_EXPR_TERNARY;
    expr->line = line;
    expr->u.ternary.cond = cond;
    expr->u.ternary.then_expr = then_expr;
    expr->u.ternary.else_expr = else_expr;
    return expr;
}

XonExpr* xon_expr_if(DataNode* cond, DataNode* then_expr, DataNode* else_expr, int line) {
    XonExpr* expr = (XonExpr*)malloc(sizeof(XonExpr));
    if (!expr) return NULL;
    expr->kind = XON_EXPR_IF;
    expr->line = line;
    expr->u.ternary.cond = cond;
    expr->u.ternary.then_expr = then_expr;
    expr->u.ternary.else_expr = else_expr;
    return expr;
}

XonExpr* xon_expr_call(DataNode* callee, DataNode* args, int line) {
    XonExpr* expr = (XonExpr*)malloc(sizeof(XonExpr));
    if (!expr) return NULL;
    expr->kind = XON_EXPR_CALL;
    expr->line = line;
    expr->u.call.callee = callee;
    expr->u.call.args = args;
    return expr;
}

XonExpr* xon_expr_function(DataNode* params, DataNode* body, int line) {
    XonExpr* expr = (XonExpr*)malloc(sizeof(XonExpr));
    if (!expr) return NULL;
    expr->kind = XON_EXPR_FUNCTION;
    expr->line = line;
    expr->u.function.params = params;
    expr->u.function.body = body;
    return expr;
}

DataNode* new_decl_node(int is_const, const char* name, DataNode* init_expr) {
    DataNode* n = new_node(TYPE_DECL);
    if (!n) return NULL;
    n->data.declaration.is_const = is_const;
    n->data.declaration.name = (char*)name;
    n->data.declaration.init_expr = init_expr;
    return n;
}

DataNode* new_param_node(const char* name) {
    DataNode* node = new_node(TYPE_STRING);
    if (!node) return NULL;
    node->data.s_val = (char*)name;
    return node;
}

 
#line 304 "src/xon.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef LBRACE
#define LBRACE                          1
#define RBRACE                          2
#define COMMA                           3
#define STRING                          4
#define COLON                           5
#define IDENTIFIER                      6
#define LET                             7
#define ASSIGN                          8
#define CONST                           9
#define LBRACKET                       10
#define RBRACKET                       11
#define QUESTION                       12
#define IF                             13
#define LPAREN                         14
#define RPAREN                         15
#define ELSE                           16
#define NULLCOALESCE                   17
#define OR                             18
#define AND                            19
#define EQEQ                           20
#define NOTEQ                          21
#define LT                             22
#define LTE                            23
#define GT                             24
#define GTE                            25
#define PLUS                           26
#define MINUS                          27
#define STAR                           28
#define SLASH                          29
#define PERCENT                        30
#define NOT                            31
#define DOT                            32
#define NUMBER                         33
#define TRUE                           34
#define FALSE                          35
#define NULL_VAL                       36
#define ARROW                          37
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    xonParserTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is xonParserTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    xonParserARG_SDECL     A static variable declaration for the %extra_argument
**    xonParserARG_PDECL     A parameter declaration for the %extra_argument
**    xonParserARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    xonParserARG_STORE     Code to store %extra_argument into yypParser
**    xonParserARG_FETCH     Code to extract %extra_argument from yypParser
**    xonParserCTX_*         As xonParserARG_ except for %extra_context
**    YYREALLOC          Name of the realloc() function to use
**    YYFREE             Name of the free() function to use
**    YYDYNSTACK         True if stack space should be extended on heap
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
**    YY_MIN_DSTRCTR     Minimum symbol value that has a destructor
**    YY_MAX_DSTRCTR     Maximum symbol value that has a destructor
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 60
#define YYACTIONTYPE unsigned char
#define xonParserTOKENTYPE Token
typedef union {
  int yyinit;
  xonParserTOKENTYPE yy0;
  DataNode* yy19;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define xonParserARG_SDECL  ParserState *pState ;
#define xonParserARG_PDECL , ParserState *pState 
#define xonParserARG_PARAM ,pState 
#define xonParserARG_FETCH  ParserState *pState =yypParser->pState ;
#define xonParserARG_STORE yypParser->pState =pState ;
#define YYREALLOC realloc
#define YYFREE free
#define YYDYNSTACK 0
#define xonParserCTX_SDECL
#define xonParserCTX_PDECL
#define xonParserCTX_PARAM
#define xonParserCTX_FETCH
#define xonParserCTX_STORE
#define YYNSTATE             77
#define YYNRULE              66
#define YYNRULE_WITH_ACTION  63
#define YYNTOKEN             38
#define YY_MAX_SHIFT         76
#define YY_MIN_SHIFTREDUCE   117
#define YY_MAX_SHIFTREDUCE   182
#define YY_ERROR_ACTION      183
#define YY_ACCEPT_ACTION     184
#define YY_NO_ACTION         185
#define YY_MIN_REDUCE        186
#define YY_MAX_REDUCE        251
#define YY_MIN_DSTRCTR       0
#define YY_MAX_DSTRCTR       0
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif

/* Macro to determine if stack space has the ability to grow using
** heap memory.
*/
#if YYSTACKDEPTH<=0 || YYDYNSTACK
# define YYGROWABLESTACK 1
#else
# define YYGROWABLESTACK 0
#endif

/* Guarantee a minimum number of initial stack slots.
*/
#if YYSTACKDEPTH<=0
# undef YYSTACKDEPTH
# define YYSTACKDEPTH 2  /* Need a minimum stack size */
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (641)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   239,  192,  187,  240,    8,   64,   64,   73,   49,   66,
 /*    10 */    45,   35,   41,   38,  225,   46,  232,    5,  239,   61,
 /*    20 */    63,  240,   52,  244,  244,   73,   49,   66,   45,   35,
 /*    30 */    41,   38,  225,   46,  232,   58,   59,  239,   26,   25,
 /*    40 */   240,   50,  200,  200,   73,   49,   66,   45,   35,   41,
 /*    50 */    38,  225,   46,  232,   33,   51,  191,  165,    6,  164,
 /*    60 */    32,   28,   27,    3,  130,   33,   71,    1,  165,   54,
 /*    70 */   164,    7,  184,   76,    3,  129,   75,   71,    1,   30,
 /*    80 */    29,   20,   19,  162,   31,  161,  166,  167,  168,  169,
 /*    90 */    30,   29,  179,   33,   60,   31,    9,  166,  167,  168,
 /*   100 */   169,  121,    3,   74,  239,   56,   55,  240,   53,  201,
 /*   110 */   201,   73,   49,   66,   45,   35,   41,   38,  225,   46,
 /*   120 */   232,  120,   62,   74,  239,   56,   55,  240,   53,  196,
 /*   130 */   196,   73,   49,   66,   45,   35,   41,   38,  225,   46,
 /*   140 */   232,   16,   17,    2,  239,  119,   34,  240,  172,  195,
 /*   150 */   195,   73,   49,   66,   45,   35,   41,   38,  225,   46,
 /*   160 */   232,   57,  247,   18,  239,   17,   12,  240,   13,  194,
 /*   170 */   194,   73,   49,   66,   45,   35,   41,   38,  225,   46,
 /*   180 */   232,   10,   14,   15,  239,   11,  186,  240,  185,  245,
 /*   190 */   245,   73,   49,   66,   45,   35,   41,   38,  225,   46,
 /*   200 */   232,  185,  185,  185,  239,  185,  185,  240,  185,  242,
 /*   210 */   242,   73,   49,   66,   45,   35,   41,   38,  225,   46,
 /*   220 */   232,  185,  185,  185,  239,  185,  185,  240,  185,   70,
 /*   230 */    70,   73,   49,   66,   45,   35,   41,   38,  225,   46,
 /*   240 */   232,  185,  185,  185,  239,  185,  185,  240,  185,  193,
 /*   250 */   193,   73,   49,   66,   45,   35,   41,   38,  225,   46,
 /*   260 */   232,   33,  185,  185,  165,  185,   65,  185,    4,  185,
 /*   270 */     3,  185,   33,   71,    1,  165,  128,  164,  185,  185,
 /*   280 */   185,    3,  185,  185,   71,    1,   30,   29,  185,  185,
 /*   290 */   185,   31,  185,  166,  167,  168,  169,   30,   29,  185,
 /*   300 */   185,  185,   31,  185,  166,  167,  168,  169,   24,   23,
 /*   310 */    22,   21,  239,  185,  185,  240,  185,  185,  203,   73,
 /*   320 */    49,   66,   45,   35,   41,   38,  225,   46,  232,  185,
 /*   330 */   185,  239,  185,  185,  240,  185,  185,   69,   73,   49,
 /*   340 */    66,   45,   35,   41,   38,  225,   46,  232,  185,  185,
 /*   350 */   185,  185,  239,  185,  185,  240,  185,  185,  202,   73,
 /*   360 */    49,   66,   45,   35,   41,   38,  225,   46,  232,  185,
 /*   370 */   185,  239,  185,  185,  240,  185,  185,   72,   73,   49,
 /*   380 */    66,   45,   35,   41,   38,  225,   46,  232,   33,  185,
 /*   390 */   185,  165,  185,  164,  185,  239,  185,    3,  240,  185,
 /*   400 */   185,    1,  185,   68,   66,   45,   35,   41,   38,  225,
 /*   410 */    46,  232,  185,   30,   29,  185,  185,  185,   31,  185,
 /*   420 */   166,  167,  168,  169,  239,  185,  185,  240,  185,  185,
 /*   430 */   185,  185,  185,   67,   45,   35,   41,   38,  225,   46,
 /*   440 */   232,  239,  185,  185,  240,  185,  185,  239,  185,  185,
 /*   450 */   240,   48,   35,   41,   38,  225,   46,  232,   36,   41,
 /*   460 */    38,  225,   46,  232,  239,  185,  185,  240,  185,  185,
 /*   470 */   185,  185,  185,  185,  185,   37,   41,   38,  225,   46,
 /*   480 */   232,  239,  185,  185,  240,  185,  185,  239,  185,  185,
 /*   490 */   240,  185,  185,   42,   38,  225,   46,  232,  185,   43,
 /*   500 */    38,  225,   46,  232,  239,  185,  185,  240,  185,  185,
 /*   510 */   185,  185,  185,  185,  185,  185,   44,   38,  225,   46,
 /*   520 */   232,  239,  185,  185,  240,  185,  185,  239,  185,  185,
 /*   530 */   240,  185,  185,   47,   38,  225,   46,  232,  185,  185,
 /*   540 */    39,  225,   46,  232,  239,  185,  185,  240,  185,  185,
 /*   550 */   185,  185,  185,  185,  185,  185,  185,   40,  225,   46,
 /*   560 */   232,  239,  185,  185,  240,  185,  185,  239,  185,  185,
 /*   570 */   240,  185,  185,  185,  185,  224,   46,  232,  185,  185,
 /*   580 */   185,  223,   46,  232,  239,  185,  185,  240,  185,  185,
 /*   590 */   185,  185,  185,  185,  185,  185,  185,  185,  228,   46,
 /*   600 */   232,  239,  185,  185,  240,  185,  185,  239,  185,  185,
 /*   610 */   240,  185,  185,  185,  185,  227,   46,  232,  185,  185,
 /*   620 */   185,  226,   46,  232,  239,  185,  185,  240,  185,  185,
 /*   630 */   185,  185,  185,  185,  185,  185,  185,  185,  222,   46,
 /*   640 */   232,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    39,   41,    0,   42,    3,   44,   45,   46,   47,   48,
 /*    10 */    49,   50,   51,   52,   53,   54,   55,    8,   39,   58,
 /*    20 */    59,   42,    6,   44,   45,   46,   47,   48,   49,   50,
 /*    30 */    51,   52,   53,   54,   55,   56,   57,   39,   26,   27,
 /*    40 */    42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
 /*    50 */    52,   53,   54,   55,    1,   40,   41,    4,    8,    6,
 /*    60 */    28,   29,   30,   10,   11,    1,   13,   14,    4,    6,
 /*    70 */     6,    5,   38,   39,   10,   11,   42,   13,   14,   26,
 /*    80 */    27,   20,   21,    6,   31,   15,   33,   34,   35,   36,
 /*    90 */    26,   27,    6,    1,    3,   31,   37,   33,   34,   35,
 /*   100 */    36,    2,   10,    4,   39,    6,    7,   42,    9,   44,
 /*   110 */    45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
 /*   120 */    55,    2,   15,    4,   39,    6,    7,   42,    9,   44,
 /*   130 */    45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
 /*   140 */    55,   17,   18,   14,   39,    2,    3,   42,   15,   44,
 /*   150 */    45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
 /*   160 */    55,   32,    3,   19,   39,   18,   16,   42,   15,   44,
 /*   170 */    45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
 /*   180 */    55,   14,    5,   12,   39,    5,    0,   42,   60,   44,
 /*   190 */    45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
 /*   200 */    55,   60,   60,   60,   39,   60,   60,   42,   60,   44,
 /*   210 */    45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
 /*   220 */    55,   60,   60,   60,   39,   60,   60,   42,   60,   44,
 /*   230 */    45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
 /*   240 */    55,   60,   60,   60,   39,   60,   60,   42,   60,   44,
 /*   250 */    45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
 /*   260 */    55,    1,   60,   60,    4,   60,    6,   60,    3,   60,
 /*   270 */    10,   60,    1,   13,   14,    4,   11,    6,   60,   60,
 /*   280 */    60,   10,   60,   60,   13,   14,   26,   27,   60,   60,
 /*   290 */    60,   31,   60,   33,   34,   35,   36,   26,   27,   60,
 /*   300 */    60,   60,   31,   60,   33,   34,   35,   36,   22,   23,
 /*   310 */    24,   25,   39,   60,   60,   42,   60,   60,   45,   46,
 /*   320 */    47,   48,   49,   50,   51,   52,   53,   54,   55,   60,
 /*   330 */    60,   39,   60,   60,   42,   60,   60,   45,   46,   47,
 /*   340 */    48,   49,   50,   51,   52,   53,   54,   55,   60,   60,
 /*   350 */    60,   60,   39,   60,   60,   42,   60,   60,   45,   46,
 /*   360 */    47,   48,   49,   50,   51,   52,   53,   54,   55,   60,
 /*   370 */    60,   39,   60,   60,   42,   60,   60,   45,   46,   47,
 /*   380 */    48,   49,   50,   51,   52,   53,   54,   55,    1,   60,
 /*   390 */    60,    4,   60,    6,   60,   39,   60,   10,   42,   60,
 /*   400 */    60,   14,   60,   47,   48,   49,   50,   51,   52,   53,
 /*   410 */    54,   55,   60,   26,   27,   60,   60,   60,   31,   60,
 /*   420 */    33,   34,   35,   36,   39,   60,   60,   42,   60,   60,
 /*   430 */    60,   60,   60,   48,   49,   50,   51,   52,   53,   54,
 /*   440 */    55,   39,   60,   60,   42,   60,   60,   39,   60,   60,
 /*   450 */    42,   49,   50,   51,   52,   53,   54,   55,   50,   51,
 /*   460 */    52,   53,   54,   55,   39,   60,   60,   42,   60,   60,
 /*   470 */    60,   60,   60,   60,   60,   50,   51,   52,   53,   54,
 /*   480 */    55,   39,   60,   60,   42,   60,   60,   39,   60,   60,
 /*   490 */    42,   60,   60,   51,   52,   53,   54,   55,   60,   51,
 /*   500 */    52,   53,   54,   55,   39,   60,   60,   42,   60,   60,
 /*   510 */    60,   60,   60,   60,   60,   60,   51,   52,   53,   54,
 /*   520 */    55,   39,   60,   60,   42,   60,   60,   39,   60,   60,
 /*   530 */    42,   60,   60,   51,   52,   53,   54,   55,   60,   60,
 /*   540 */    52,   53,   54,   55,   39,   60,   60,   42,   60,   60,
 /*   550 */    60,   60,   60,   60,   60,   60,   60,   52,   53,   54,
 /*   560 */    55,   39,   60,   60,   42,   60,   60,   39,   60,   60,
 /*   570 */    42,   60,   60,   60,   60,   53,   54,   55,   60,   60,
 /*   580 */    60,   53,   54,   55,   39,   60,   60,   42,   60,   60,
 /*   590 */    60,   60,   60,   60,   60,   60,   60,   60,   53,   54,
 /*   600 */    55,   39,   60,   60,   42,   60,   60,   39,   60,   60,
 /*   610 */    42,   60,   60,   60,   60,   53,   54,   55,   60,   60,
 /*   620 */    60,   53,   54,   55,   39,   60,   60,   42,   60,   60,
 /*   630 */    60,   60,   60,   60,   60,   60,   60,   60,   53,   54,
 /*   640 */    55,   38,   38,   38,   38,   38,   38,   38,   38,   38,
 /*   650 */    38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
 /*   660 */    38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
 /*   670 */    38,   38,   38,   38,   38,   38,   38,   38,   38,
};
#define YY_SHIFT_COUNT    (76)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (387)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */    92,  260,  271,   53,   64,  271,  271,  271,  271,  271,
 /*    10 */   271,  271,  271,  271,  271,  271,  387,  387,  387,  387,
 /*    20 */   387,  387,  387,  387,  387,  387,  387,  387,  387,  387,
 /*    30 */   387,  387,  387,   99,  119,  286,  286,  286,   32,   32,
 /*    40 */    32,   12,   12,   12,   12,   61,  129,   12,   61,  124,
 /*    50 */   265,  143,    9,   16,   50,   63,   66,   77,    1,   70,
 /*    60 */    86,   91,   59,  107,  133,  159,  144,  144,  147,  150,
 /*    70 */   153,  167,  177,  171,  180,    2,  186,
};
#define YY_REDUCE_COUNT (34)
#define YY_REDUCE_MIN   (-40)
#define YY_REDUCE_MAX   (585)
static const short yy_reduce_ofst[] = {
 /*     0 */    34,  -39,  -21,   -2,   65,   85,  105,  125,  145,  165,
 /*    10 */   185,  205,  273,  292,  313,  332,  356,  385,  402,  408,
 /*    20 */   425,  442,  448,  465,  482,  488,  505,  522,  528,  545,
 /*    30 */   562,  568,  585,   15,  -40,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   183,  246,  243,  183,  183,  183,  183,  183,  183,  183,
 /*    10 */   183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
 /*    20 */   183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
 /*    30 */   183,  183,  183,  183,  183,  213,  212,  211,  221,  220,
 /*    40 */   219,  218,  217,  216,  215,  210,  229,  214,  209,  205,
 /*    50 */   183,  183,  183,  183,  183,  183,  183,  183,  250,  183,
 /*    60 */   183,  251,  183,  183,  183,  233,  208,  207,  206,  183,
 /*    70 */   183,  183,  183,  204,  183,  183,  183,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  xonParserARG_SDECL                /* A place to hold %extra_argument */
  xonParserCTX_SDECL                /* A place to hold %extra_context */
  yyStackEntry *yystackEnd;           /* Last entry in the stack */
  yyStackEntry *yystack;              /* The parser stack */
  yyStackEntry yystk0[YYSTACKDEPTH];  /* Initial stack space */
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void xonParserTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "LBRACE",
  /*    2 */ "RBRACE",
  /*    3 */ "COMMA",
  /*    4 */ "STRING",
  /*    5 */ "COLON",
  /*    6 */ "IDENTIFIER",
  /*    7 */ "LET",
  /*    8 */ "ASSIGN",
  /*    9 */ "CONST",
  /*   10 */ "LBRACKET",
  /*   11 */ "RBRACKET",
  /*   12 */ "QUESTION",
  /*   13 */ "IF",
  /*   14 */ "LPAREN",
  /*   15 */ "RPAREN",
  /*   16 */ "ELSE",
  /*   17 */ "NULLCOALESCE",
  /*   18 */ "OR",
  /*   19 */ "AND",
  /*   20 */ "EQEQ",
  /*   21 */ "NOTEQ",
  /*   22 */ "LT",
  /*   23 */ "LTE",
  /*   24 */ "GT",
  /*   25 */ "GTE",
  /*   26 */ "PLUS",
  /*   27 */ "MINUS",
  /*   28 */ "STAR",
  /*   29 */ "SLASH",
  /*   30 */ "PERCENT",
  /*   31 */ "NOT",
  /*   32 */ "DOT",
  /*   33 */ "NUMBER",
  /*   34 */ "TRUE",
  /*   35 */ "FALSE",
  /*   36 */ "NULL_VAL",
  /*   37 */ "ARROW",
  /*   38 */ "root",
  /*   39 */ "object",
  /*   40 */ "pair_list",
  /*   41 */ "pair",
  /*   42 */ "list",
  /*   43 */ "value_list",
  /*   44 */ "expr",
  /*   45 */ "ternary_expr",
  /*   46 */ "nullish_expr",
  /*   47 */ "or_expr",
  /*   48 */ "and_expr",
  /*   49 */ "eq_expr",
  /*   50 */ "rel_expr",
  /*   51 */ "add_expr",
  /*   52 */ "mul_expr",
  /*   53 */ "unary_expr",
  /*   54 */ "postfix_expr",
  /*   55 */ "primary_expr",
  /*   56 */ "arg_list",
  /*   57 */ "arg_list_opt",
  /*   58 */ "param_list",
  /*   59 */ "param_list_opt",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "root ::= object",
 /*   1 */ "root ::= list",
 /*   2 */ "object ::= LBRACE pair_list RBRACE",
 /*   3 */ "object ::= LBRACE pair_list COMMA RBRACE",
 /*   4 */ "object ::= LBRACE RBRACE",
 /*   5 */ "pair_list ::= pair",
 /*   6 */ "pair_list ::= pair_list COMMA pair",
 /*   7 */ "pair ::= STRING COLON expr",
 /*   8 */ "pair ::= IDENTIFIER COLON expr",
 /*   9 */ "pair ::= LET IDENTIFIER ASSIGN expr",
 /*  10 */ "pair ::= CONST IDENTIFIER ASSIGN expr",
 /*  11 */ "list ::= LBRACKET value_list RBRACKET",
 /*  12 */ "list ::= LBRACKET value_list COMMA RBRACKET",
 /*  13 */ "list ::= LBRACKET RBRACKET",
 /*  14 */ "value_list ::= expr",
 /*  15 */ "value_list ::= value_list COMMA expr",
 /*  16 */ "ternary_expr ::= nullish_expr QUESTION ternary_expr COLON ternary_expr",
 /*  17 */ "ternary_expr ::= IF LPAREN expr RPAREN ternary_expr ELSE ternary_expr",
 /*  18 */ "ternary_expr ::= nullish_expr",
 /*  19 */ "nullish_expr ::= or_expr",
 /*  20 */ "nullish_expr ::= or_expr NULLCOALESCE or_expr",
 /*  21 */ "or_expr ::= or_expr OR and_expr",
 /*  22 */ "or_expr ::= and_expr",
 /*  23 */ "and_expr ::= and_expr AND eq_expr",
 /*  24 */ "and_expr ::= eq_expr",
 /*  25 */ "eq_expr ::= eq_expr EQEQ rel_expr",
 /*  26 */ "eq_expr ::= eq_expr NOTEQ rel_expr",
 /*  27 */ "eq_expr ::= rel_expr",
 /*  28 */ "rel_expr ::= rel_expr LT add_expr",
 /*  29 */ "rel_expr ::= rel_expr LTE add_expr",
 /*  30 */ "rel_expr ::= rel_expr GT add_expr",
 /*  31 */ "rel_expr ::= rel_expr GTE add_expr",
 /*  32 */ "rel_expr ::= add_expr",
 /*  33 */ "add_expr ::= add_expr PLUS mul_expr",
 /*  34 */ "add_expr ::= add_expr MINUS mul_expr",
 /*  35 */ "add_expr ::= mul_expr",
 /*  36 */ "mul_expr ::= mul_expr STAR unary_expr",
 /*  37 */ "mul_expr ::= mul_expr SLASH unary_expr",
 /*  38 */ "mul_expr ::= mul_expr PERCENT unary_expr",
 /*  39 */ "mul_expr ::= unary_expr",
 /*  40 */ "unary_expr ::= NOT unary_expr",
 /*  41 */ "unary_expr ::= PLUS unary_expr",
 /*  42 */ "unary_expr ::= MINUS unary_expr",
 /*  43 */ "unary_expr ::= postfix_expr",
 /*  44 */ "postfix_expr ::= postfix_expr LPAREN arg_list_opt RPAREN",
 /*  45 */ "postfix_expr ::= postfix_expr DOT IDENTIFIER",
 /*  46 */ "postfix_expr ::= primary_expr",
 /*  47 */ "primary_expr ::= IDENTIFIER",
 /*  48 */ "primary_expr ::= STRING",
 /*  49 */ "primary_expr ::= NUMBER",
 /*  50 */ "primary_expr ::= TRUE",
 /*  51 */ "primary_expr ::= FALSE",
 /*  52 */ "primary_expr ::= NULL_VAL",
 /*  53 */ "primary_expr ::= object",
 /*  54 */ "primary_expr ::= list",
 /*  55 */ "primary_expr ::= LPAREN expr RPAREN",
 /*  56 */ "primary_expr ::= LPAREN param_list_opt RPAREN ARROW expr",
 /*  57 */ "arg_list_opt ::=",
 /*  58 */ "arg_list ::= expr",
 /*  59 */ "arg_list ::= arg_list COMMA expr",
 /*  60 */ "param_list_opt ::=",
 /*  61 */ "param_list ::= IDENTIFIER",
 /*  62 */ "param_list ::= param_list COMMA IDENTIFIER",
 /*  63 */ "expr ::= ternary_expr",
 /*  64 */ "arg_list_opt ::= arg_list",
 /*  65 */ "param_list_opt ::= param_list",
};
#endif /* NDEBUG */


#if YYGROWABLESTACK
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int oldSize = 1 + (int)(p->yystackEnd - p->yystack);
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = oldSize*2 + 100;
  idx = (int)(p->yytos - p->yystack);
  if( p->yystack==p->yystk0 ){
    pNew = YYREALLOC(0, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
    memcpy(pNew, p->yystack, oldSize*sizeof(pNew[0]));
  }else{
    pNew = YYREALLOC(p->yystack, newSize*sizeof(pNew[0]));
    if( pNew==0 ) return 1;
  }
  p->yystack = pNew;
  p->yytos = &p->yystack[idx];
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
            yyTracePrompt, oldSize, newSize);
  }
#endif
  p->yystackEnd = &p->yystack[newSize-1];
  return 0;
}
#endif /* YYGROWABLESTACK */

#if !YYGROWABLESTACK
/* For builds that do no have a growable stack, yyGrowStack always
** returns an error.
*/
# define yyGrowStack(X) 1
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to xonParserAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void xonParserInit(void *yypRawParser xonParserCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  xonParserCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
  yypParser->yystack = yypParser->yystk0;
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
}

#ifndef xonParser_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to xonParser and xonParserFree.
*/
void *xonParserAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) xonParserCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    xonParserCTX_STORE
    xonParserInit(yypParser xonParserCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* xonParser_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  xonParserARG_FETCH
  xonParserCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void xonParserFinalize(void *p){
  yyParser *pParser = (yyParser*)p;

  /* In-lined version of calling yy_pop_parser_stack() for each
  ** element left in the stack */
  yyStackEntry *yytos = pParser->yytos;
  while( yytos>pParser->yystack ){
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sPopping %s\n",
        yyTracePrompt,
        yyTokenName[yytos->major]);
    }
#endif
    if( yytos->major>=YY_MIN_DSTRCTR ){
      yy_destructor(pParser, yytos->major, &yytos->minor);
    }
    yytos--;
  }

#if YYGROWABLESTACK
  if( pParser->yystack!=pParser->yystk0 ) YYFREE(pParser->yystack);
#endif
}

#ifndef xonParser_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void xonParserFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  xonParserFinalize(p);
  (*freeProc)(p);
}
#endif /* xonParser_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int xonParserStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int xonParserCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   xonParserARG_FETCH
   xonParserCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   xonParserARG_STORE /* Suppress warning about unused %extra_argument var */
   xonParserCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  xonParserTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
  yytos = yypParser->yytos;
  if( yytos>yypParser->yystackEnd ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
    yytos = yypParser->yytos;
    assert( yytos <= yypParser->yystackEnd );
  }
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    38,  /* (0) root ::= object */
    38,  /* (1) root ::= list */
    39,  /* (2) object ::= LBRACE pair_list RBRACE */
    39,  /* (3) object ::= LBRACE pair_list COMMA RBRACE */
    39,  /* (4) object ::= LBRACE RBRACE */
    40,  /* (5) pair_list ::= pair */
    40,  /* (6) pair_list ::= pair_list COMMA pair */
    41,  /* (7) pair ::= STRING COLON expr */
    41,  /* (8) pair ::= IDENTIFIER COLON expr */
    41,  /* (9) pair ::= LET IDENTIFIER ASSIGN expr */
    41,  /* (10) pair ::= CONST IDENTIFIER ASSIGN expr */
    42,  /* (11) list ::= LBRACKET value_list RBRACKET */
    42,  /* (12) list ::= LBRACKET value_list COMMA RBRACKET */
    42,  /* (13) list ::= LBRACKET RBRACKET */
    43,  /* (14) value_list ::= expr */
    43,  /* (15) value_list ::= value_list COMMA expr */
    45,  /* (16) ternary_expr ::= nullish_expr QUESTION ternary_expr COLON ternary_expr */
    45,  /* (17) ternary_expr ::= IF LPAREN expr RPAREN ternary_expr ELSE ternary_expr */
    45,  /* (18) ternary_expr ::= nullish_expr */
    46,  /* (19) nullish_expr ::= or_expr */
    46,  /* (20) nullish_expr ::= or_expr NULLCOALESCE or_expr */
    47,  /* (21) or_expr ::= or_expr OR and_expr */
    47,  /* (22) or_expr ::= and_expr */
    48,  /* (23) and_expr ::= and_expr AND eq_expr */
    48,  /* (24) and_expr ::= eq_expr */
    49,  /* (25) eq_expr ::= eq_expr EQEQ rel_expr */
    49,  /* (26) eq_expr ::= eq_expr NOTEQ rel_expr */
    49,  /* (27) eq_expr ::= rel_expr */
    50,  /* (28) rel_expr ::= rel_expr LT add_expr */
    50,  /* (29) rel_expr ::= rel_expr LTE add_expr */
    50,  /* (30) rel_expr ::= rel_expr GT add_expr */
    50,  /* (31) rel_expr ::= rel_expr GTE add_expr */
    50,  /* (32) rel_expr ::= add_expr */
    51,  /* (33) add_expr ::= add_expr PLUS mul_expr */
    51,  /* (34) add_expr ::= add_expr MINUS mul_expr */
    51,  /* (35) add_expr ::= mul_expr */
    52,  /* (36) mul_expr ::= mul_expr STAR unary_expr */
    52,  /* (37) mul_expr ::= mul_expr SLASH unary_expr */
    52,  /* (38) mul_expr ::= mul_expr PERCENT unary_expr */
    52,  /* (39) mul_expr ::= unary_expr */
    53,  /* (40) unary_expr ::= NOT unary_expr */
    53,  /* (41) unary_expr ::= PLUS unary_expr */
    53,  /* (42) unary_expr ::= MINUS unary_expr */
    53,  /* (43) unary_expr ::= postfix_expr */
    54,  /* (44) postfix_expr ::= postfix_expr LPAREN arg_list_opt RPAREN */
    54,  /* (45) postfix_expr ::= postfix_expr DOT IDENTIFIER */
    54,  /* (46) postfix_expr ::= primary_expr */
    55,  /* (47) primary_expr ::= IDENTIFIER */
    55,  /* (48) primary_expr ::= STRING */
    55,  /* (49) primary_expr ::= NUMBER */
    55,  /* (50) primary_expr ::= TRUE */
    55,  /* (51) primary_expr ::= FALSE */
    55,  /* (52) primary_expr ::= NULL_VAL */
    55,  /* (53) primary_expr ::= object */
    55,  /* (54) primary_expr ::= list */
    55,  /* (55) primary_expr ::= LPAREN expr RPAREN */
    55,  /* (56) primary_expr ::= LPAREN param_list_opt RPAREN ARROW expr */
    57,  /* (57) arg_list_opt ::= */
    56,  /* (58) arg_list ::= expr */
    56,  /* (59) arg_list ::= arg_list COMMA expr */
    59,  /* (60) param_list_opt ::= */
    58,  /* (61) param_list ::= IDENTIFIER */
    58,  /* (62) param_list ::= param_list COMMA IDENTIFIER */
    44,  /* (63) expr ::= ternary_expr */
    57,  /* (64) arg_list_opt ::= arg_list */
    59,  /* (65) param_list_opt ::= param_list */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) root ::= object */
   -1,  /* (1) root ::= list */
   -3,  /* (2) object ::= LBRACE pair_list RBRACE */
   -4,  /* (3) object ::= LBRACE pair_list COMMA RBRACE */
   -2,  /* (4) object ::= LBRACE RBRACE */
   -1,  /* (5) pair_list ::= pair */
   -3,  /* (6) pair_list ::= pair_list COMMA pair */
   -3,  /* (7) pair ::= STRING COLON expr */
   -3,  /* (8) pair ::= IDENTIFIER COLON expr */
   -4,  /* (9) pair ::= LET IDENTIFIER ASSIGN expr */
   -4,  /* (10) pair ::= CONST IDENTIFIER ASSIGN expr */
   -3,  /* (11) list ::= LBRACKET value_list RBRACKET */
   -4,  /* (12) list ::= LBRACKET value_list COMMA RBRACKET */
   -2,  /* (13) list ::= LBRACKET RBRACKET */
   -1,  /* (14) value_list ::= expr */
   -3,  /* (15) value_list ::= value_list COMMA expr */
   -5,  /* (16) ternary_expr ::= nullish_expr QUESTION ternary_expr COLON ternary_expr */
   -7,  /* (17) ternary_expr ::= IF LPAREN expr RPAREN ternary_expr ELSE ternary_expr */
   -1,  /* (18) ternary_expr ::= nullish_expr */
   -1,  /* (19) nullish_expr ::= or_expr */
   -3,  /* (20) nullish_expr ::= or_expr NULLCOALESCE or_expr */
   -3,  /* (21) or_expr ::= or_expr OR and_expr */
   -1,  /* (22) or_expr ::= and_expr */
   -3,  /* (23) and_expr ::= and_expr AND eq_expr */
   -1,  /* (24) and_expr ::= eq_expr */
   -3,  /* (25) eq_expr ::= eq_expr EQEQ rel_expr */
   -3,  /* (26) eq_expr ::= eq_expr NOTEQ rel_expr */
   -1,  /* (27) eq_expr ::= rel_expr */
   -3,  /* (28) rel_expr ::= rel_expr LT add_expr */
   -3,  /* (29) rel_expr ::= rel_expr LTE add_expr */
   -3,  /* (30) rel_expr ::= rel_expr GT add_expr */
   -3,  /* (31) rel_expr ::= rel_expr GTE add_expr */
   -1,  /* (32) rel_expr ::= add_expr */
   -3,  /* (33) add_expr ::= add_expr PLUS mul_expr */
   -3,  /* (34) add_expr ::= add_expr MINUS mul_expr */
   -1,  /* (35) add_expr ::= mul_expr */
   -3,  /* (36) mul_expr ::= mul_expr STAR unary_expr */
   -3,  /* (37) mul_expr ::= mul_expr SLASH unary_expr */
   -3,  /* (38) mul_expr ::= mul_expr PERCENT unary_expr */
   -1,  /* (39) mul_expr ::= unary_expr */
   -2,  /* (40) unary_expr ::= NOT unary_expr */
   -2,  /* (41) unary_expr ::= PLUS unary_expr */
   -2,  /* (42) unary_expr ::= MINUS unary_expr */
   -1,  /* (43) unary_expr ::= postfix_expr */
   -4,  /* (44) postfix_expr ::= postfix_expr LPAREN arg_list_opt RPAREN */
   -3,  /* (45) postfix_expr ::= postfix_expr DOT IDENTIFIER */
   -1,  /* (46) postfix_expr ::= primary_expr */
   -1,  /* (47) primary_expr ::= IDENTIFIER */
   -1,  /* (48) primary_expr ::= STRING */
   -1,  /* (49) primary_expr ::= NUMBER */
   -1,  /* (50) primary_expr ::= TRUE */
   -1,  /* (51) primary_expr ::= FALSE */
   -1,  /* (52) primary_expr ::= NULL_VAL */
   -1,  /* (53) primary_expr ::= object */
   -1,  /* (54) primary_expr ::= list */
   -3,  /* (55) primary_expr ::= LPAREN expr RPAREN */
   -5,  /* (56) primary_expr ::= LPAREN param_list_opt RPAREN ARROW expr */
    0,  /* (57) arg_list_opt ::= */
   -1,  /* (58) arg_list ::= expr */
   -3,  /* (59) arg_list ::= arg_list COMMA expr */
    0,  /* (60) param_list_opt ::= */
   -1,  /* (61) param_list ::= IDENTIFIER */
   -3,  /* (62) param_list ::= param_list COMMA IDENTIFIER */
   -1,  /* (63) expr ::= ternary_expr */
   -1,  /* (64) arg_list_opt ::= arg_list */
   -1,  /* (65) param_list_opt ::= param_list */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  xonParserTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  xonParserCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  xonParserARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* root ::= object */
      case 1: /* root ::= list */ yytestcase(yyruleno==1);
#line 323 "src/xon.lemon"
{ *pState->result = yymsp[0].minor.yy19; }
#line 1535 "src/xon.c"
        break;
      case 2: /* object ::= LBRACE pair_list RBRACE */
      case 55: /* primary_expr ::= LPAREN expr RPAREN */ yytestcase(yyruleno==55);
#line 327 "src/xon.lemon"
{ yymsp[-2].minor.yy19 = yymsp[-1].minor.yy19; }
#line 1541 "src/xon.c"
        break;
      case 3: /* object ::= LBRACE pair_list COMMA RBRACE */
#line 328 "src/xon.lemon"
{ yymsp[-3].minor.yy19 = yymsp[-2].minor.yy19; }
#line 1546 "src/xon.c"
        break;
      case 4: /* object ::= LBRACE RBRACE */
#line 329 "src/xon.lemon"
{ yymsp[-1].minor.yy19 = new_node(TYPE_OBJECT); }
#line 1551 "src/xon.c"
        break;
      case 5: /* pair_list ::= pair */
#line 331 "src/xon.lemon"
{
    yylhsminor.yy19 = new_node(TYPE_OBJECT);
    if (yylhsminor.yy19) yylhsminor.yy19->data.aggregate.value = yymsp[0].minor.yy19;
}
#line 1559 "src/xon.c"
  yymsp[0].minor.yy19 = yylhsminor.yy19;
        break;
      case 6: /* pair_list ::= pair_list COMMA pair */
#line 335 "src/xon.lemon"
{
    yylhsminor.yy19 = yymsp[-2].minor.yy19;
    link_node(yylhsminor.yy19->data.aggregate.value, yymsp[0].minor.yy19);
}
#line 1568 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 7: /* pair ::= STRING COLON expr */
      case 8: /* pair ::= IDENTIFIER COLON expr */ yytestcase(yyruleno==8);
#line 340 "src/xon.lemon"
{
    yylhsminor.yy19 = new_pair_node(yymsp[-2].minor.yy0.s_val, yymsp[0].minor.yy19);
}
#line 1577 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 9: /* pair ::= LET IDENTIFIER ASSIGN expr */
#line 346 "src/xon.lemon"
{
    yymsp[-3].minor.yy19 = new_decl_node(0, yymsp[-2].minor.yy0.s_val, yymsp[0].minor.yy19);
}
#line 1585 "src/xon.c"
        break;
      case 10: /* pair ::= CONST IDENTIFIER ASSIGN expr */
#line 349 "src/xon.lemon"
{
    yymsp[-3].minor.yy19 = new_decl_node(1, yymsp[-2].minor.yy0.s_val, yymsp[0].minor.yy19);
}
#line 1592 "src/xon.c"
        break;
      case 11: /* list ::= LBRACKET value_list RBRACKET */
#line 354 "src/xon.lemon"
{
    yymsp[-2].minor.yy19 = new_node(TYPE_LIST);
    if (yymsp[-2].minor.yy19) yymsp[-2].minor.yy19->data.aggregate.value = yymsp[-1].minor.yy19;
}
#line 1600 "src/xon.c"
        break;
      case 12: /* list ::= LBRACKET value_list COMMA RBRACKET */
#line 358 "src/xon.lemon"
{
    yymsp[-3].minor.yy19 = new_node(TYPE_LIST);
    if (yymsp[-3].minor.yy19) yymsp[-3].minor.yy19->data.aggregate.value = yymsp[-2].minor.yy19;
}
#line 1608 "src/xon.c"
        break;
      case 13: /* list ::= LBRACKET RBRACKET */
#line 362 "src/xon.lemon"
{ yymsp[-1].minor.yy19 = new_node(TYPE_LIST); }
#line 1613 "src/xon.c"
        break;
      case 14: /* value_list ::= expr */
      case 18: /* ternary_expr ::= nullish_expr */ yytestcase(yyruleno==18);
      case 19: /* nullish_expr ::= or_expr */ yytestcase(yyruleno==19);
      case 22: /* or_expr ::= and_expr */ yytestcase(yyruleno==22);
      case 24: /* and_expr ::= eq_expr */ yytestcase(yyruleno==24);
      case 27: /* eq_expr ::= rel_expr */ yytestcase(yyruleno==27);
      case 32: /* rel_expr ::= add_expr */ yytestcase(yyruleno==32);
      case 35: /* add_expr ::= mul_expr */ yytestcase(yyruleno==35);
      case 39: /* mul_expr ::= unary_expr */ yytestcase(yyruleno==39);
      case 43: /* unary_expr ::= postfix_expr */ yytestcase(yyruleno==43);
      case 46: /* postfix_expr ::= primary_expr */ yytestcase(yyruleno==46);
      case 53: /* primary_expr ::= object */ yytestcase(yyruleno==53);
      case 54: /* primary_expr ::= list */ yytestcase(yyruleno==54);
      case 58: /* arg_list ::= expr */ yytestcase(yyruleno==58);
#line 364 "src/xon.lemon"
{ yylhsminor.yy19 = yymsp[0].minor.yy19; }
#line 1631 "src/xon.c"
  yymsp[0].minor.yy19 = yylhsminor.yy19;
        break;
      case 15: /* value_list ::= value_list COMMA expr */
      case 59: /* arg_list ::= arg_list COMMA expr */ yytestcase(yyruleno==59);
#line 365 "src/xon.lemon"
{ yylhsminor.yy19 = link_node(yymsp[-2].minor.yy19, yymsp[0].minor.yy19); }
#line 1638 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 16: /* ternary_expr ::= nullish_expr QUESTION ternary_expr COLON ternary_expr */
#line 370 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_ternary(yymsp[-4].minor.yy19, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, yymsp[-4].minor.yy19 ? 0 : 0));
}
#line 1646 "src/xon.c"
  yymsp[-4].minor.yy19 = yylhsminor.yy19;
        break;
      case 17: /* ternary_expr ::= IF LPAREN expr RPAREN ternary_expr ELSE ternary_expr */
#line 373 "src/xon.lemon"
{
    yymsp[-6].minor.yy19 = new_expr_node(xon_expr_if(yymsp[-4].minor.yy19, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, yymsp[-4].minor.yy19 ? 0 : 0));
}
#line 1654 "src/xon.c"
        break;
      case 20: /* nullish_expr ::= or_expr NULLCOALESCE or_expr */
#line 379 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_NULLISH, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1661 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 21: /* or_expr ::= or_expr OR and_expr */
#line 383 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_OR, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1669 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 23: /* and_expr ::= and_expr AND eq_expr */
#line 388 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_AND, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1677 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 25: /* eq_expr ::= eq_expr EQEQ rel_expr */
#line 393 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_EQ, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1685 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 26: /* eq_expr ::= eq_expr NOTEQ rel_expr */
#line 396 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_NEQ, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1693 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 28: /* rel_expr ::= rel_expr LT add_expr */
#line 401 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_LT, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1701 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 29: /* rel_expr ::= rel_expr LTE add_expr */
#line 404 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_LTE, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1709 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 30: /* rel_expr ::= rel_expr GT add_expr */
#line 407 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_GT, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1717 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 31: /* rel_expr ::= rel_expr GTE add_expr */
#line 410 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_GTE, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1725 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 33: /* add_expr ::= add_expr PLUS mul_expr */
#line 415 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_ADD, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1733 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 34: /* add_expr ::= add_expr MINUS mul_expr */
#line 418 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_SUB, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1741 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 36: /* mul_expr ::= mul_expr STAR unary_expr */
#line 423 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_MUL, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1749 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 37: /* mul_expr ::= mul_expr SLASH unary_expr */
#line 426 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_DIV, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1757 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 38: /* mul_expr ::= mul_expr PERCENT unary_expr */
#line 429 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_binary(XON_EXPR_OP_MOD, yymsp[-2].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1765 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 40: /* unary_expr ::= NOT unary_expr */
#line 434 "src/xon.lemon"
{
    yymsp[-1].minor.yy19 = new_expr_node(xon_expr_unary(XON_EXPR_OP_NOT, yymsp[0].minor.yy19, 0));
}
#line 1773 "src/xon.c"
        break;
      case 41: /* unary_expr ::= PLUS unary_expr */
#line 437 "src/xon.lemon"
{
    yymsp[-1].minor.yy19 = new_expr_node(xon_expr_unary(XON_EXPR_OP_UNARY_PLUS, yymsp[0].minor.yy19, 0));
}
#line 1780 "src/xon.c"
        break;
      case 42: /* unary_expr ::= MINUS unary_expr */
#line 440 "src/xon.lemon"
{
    yymsp[-1].minor.yy19 = new_expr_node(xon_expr_unary(XON_EXPR_OP_NEG, yymsp[0].minor.yy19, 0));
}
#line 1787 "src/xon.c"
        break;
      case 44: /* postfix_expr ::= postfix_expr LPAREN arg_list_opt RPAREN */
#line 445 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_call(yymsp[-3].minor.yy19, yymsp[-1].minor.yy19, 0));
}
#line 1794 "src/xon.c"
  yymsp[-3].minor.yy19 = yylhsminor.yy19;
        break;
      case 45: /* postfix_expr ::= postfix_expr DOT IDENTIFIER */
#line 448 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_member(yymsp[-2].minor.yy19, yymsp[0].minor.yy0.s_val, 0));
}
#line 1802 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      case 47: /* primary_expr ::= IDENTIFIER */
#line 453 "src/xon.lemon"
{
    yylhsminor.yy19 = new_expr_node(xon_expr_identifier(yymsp[0].minor.yy0.s_val, yymsp[0].minor.yy0.line));
}
#line 1810 "src/xon.c"
  yymsp[0].minor.yy19 = yylhsminor.yy19;
        break;
      case 48: /* primary_expr ::= STRING */
#line 456 "src/xon.lemon"
{
    yylhsminor.yy19 = new_node(TYPE_STRING);
    if (yylhsminor.yy19) yylhsminor.yy19->data.s_val = yymsp[0].minor.yy0.s_val;
}
#line 1819 "src/xon.c"
  yymsp[0].minor.yy19 = yylhsminor.yy19;
        break;
      case 49: /* primary_expr ::= NUMBER */
#line 460 "src/xon.lemon"
{
    yylhsminor.yy19 = new_node(TYPE_NUMBER);
    if (yylhsminor.yy19) yylhsminor.yy19->data.n_val = yymsp[0].minor.yy0.n_val;
}
#line 1828 "src/xon.c"
  yymsp[0].minor.yy19 = yylhsminor.yy19;
        break;
      case 50: /* primary_expr ::= TRUE */
#line 464 "src/xon.lemon"
{
    yymsp[0].minor.yy19 = new_node(TYPE_BOOL);
    if (yymsp[0].minor.yy19) yymsp[0].minor.yy19->data.b_val = 1;
}
#line 1837 "src/xon.c"
        break;
      case 51: /* primary_expr ::= FALSE */
#line 468 "src/xon.lemon"
{
    yymsp[0].minor.yy19 = new_node(TYPE_BOOL);
    if (yymsp[0].minor.yy19) yymsp[0].minor.yy19->data.b_val = 0;
}
#line 1845 "src/xon.c"
        break;
      case 52: /* primary_expr ::= NULL_VAL */
#line 472 "src/xon.lemon"
{
    yymsp[0].minor.yy19 = new_node(TYPE_NULL);
}
#line 1852 "src/xon.c"
        break;
      case 56: /* primary_expr ::= LPAREN param_list_opt RPAREN ARROW expr */
#line 478 "src/xon.lemon"
{
    yymsp[-4].minor.yy19 = new_expr_node(xon_expr_function(yymsp[-3].minor.yy19, yymsp[0].minor.yy19, 0));
}
#line 1859 "src/xon.c"
        break;
      case 57: /* arg_list_opt ::= */
      case 60: /* param_list_opt ::= */ yytestcase(yyruleno==60);
#line 482 "src/xon.lemon"
{ yymsp[1].minor.yy19 = NULL; }
#line 1865 "src/xon.c"
        break;
      case 61: /* param_list ::= IDENTIFIER */
#line 491 "src/xon.lemon"
{
    yylhsminor.yy19 = new_list_node(new_param_node(yymsp[0].minor.yy0.s_val));
}
#line 1872 "src/xon.c"
  yymsp[0].minor.yy19 = yylhsminor.yy19;
        break;
      case 62: /* param_list ::= param_list COMMA IDENTIFIER */
#line 494 "src/xon.lemon"
{
    yylhsminor.yy19 = yymsp[-2].minor.yy19;
    link_node(yylhsminor.yy19->data.aggregate.value, new_param_node(yymsp[0].minor.yy0.s_val));
}
#line 1881 "src/xon.c"
  yymsp[-2].minor.yy19 = yylhsminor.yy19;
        break;
      default:
      /* (63) expr ::= ternary_expr (OPTIMIZED OUT) */ assert(yyruleno!=63);
      /* (64) arg_list_opt ::= arg_list */ yytestcase(yyruleno==64);
      /* (65) param_list_opt ::= param_list */ yytestcase(yyruleno==65);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  xonParserARG_FETCH
  xonParserCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 18 "src/xon.lemon"

    pState->had_error = 1;
    if (pState->result) *pState->result = NULL;
#line 1933 "src/xon.c"
/************ End %parse_failure code *****************************************/
  xonParserARG_STORE /* Suppress warning about unused %extra_argument variable */
  xonParserCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  xonParserTOKENTYPE yyminor         /* The minor type of the error token */
){
  xonParserARG_FETCH
  xonParserCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 7 "src/xon.lemon"

    const char* token_text = TOKEN.s_val ? TOKEN.s_val : "unknown";
    pState->had_error = 1;
    if (pState->result) *pState->result = NULL;
    if (pState->on_syntax_error) {
        pState->on_syntax_error(TOKEN.line, token_text, pState->user_data);
    } else {
        fprintf(stderr, "Syntax Error at line %d near token '%s'\n", TOKEN.line, token_text);
    }
#line 1962 "src/xon.c"
/************ End %syntax_error code ******************************************/
  xonParserARG_STORE /* Suppress warning about unused %extra_argument variable */
  xonParserCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  xonParserARG_FETCH
  xonParserCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  xonParserARG_STORE /* Suppress warning about unused %extra_argument variable */
  xonParserCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "xonParserAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void xonParser(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  xonParserTOKENTYPE yyminor       /* The value for the token */
  xonParserARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  xonParserCTX_FETCH
  xonParserARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
        if( yypParser->yytos>=yypParser->yystackEnd ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor xonParserCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int xonParserFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
