#define LBRACE                           1
#define RBRACE                           2
#define COMMA                            3
#define STRING                           4
#define COLON                            5
#define IDENTIFIER                       6
#define LET                              7
#define ASSIGN                           8
#define CONST                            9
#define LBRACKET                        10
#define RBRACKET                        11
#define QUESTION                        12
#define IF                              13
#define LPAREN                          14
#define RPAREN                          15
#define ELSE                            16
#define NULLCOALESCE                    17
#define OR                              18
#define AND                             19
#define EQEQ                            20
#define NOTEQ                           21
#define LT                              22
#define LTE                             23
#define GT                              24
#define GTE                             25
#define PLUS                            26
#define MINUS                           27
#define STAR                            28
#define SLASH                           29
#define PERCENT                         30
#define NOT                             31
#define DOT                             32
#define NUMBER                          33
#define TRUE                            34
#define FALSE                           35
#define NULL_VAL                        36
#define ARROW                           37
